name: Publish
on:
  release:
    types: [ released, prereleased ]
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    permissions:
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set gradlew executable
        run: chmod +x gradlew
      - name: Publish to GitHub Packages
        continue-on-error: true
        run: |
          ./gradlew publishAllPublicationsToGitHubPackagesRepository --continue
      - name: Publish to Maven Central
        run: |
          ./gradlew publishToMavenCentral --no-configuration-cache
    env:
      ORG_GRADLE_PROJECT_publishSigningMode: inMemory
      ORG_GRADLE_PROJECT_gitHubPackagesUsername: xfqwdsj
      ORG_GRADLE_PROJECT_gitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
